# Change these first
owner: SecurosysFernandez # Your GitHub organization or username, where this repository lives
repo: clouds-uptime # The name of this repository

sites:
  - name: Securosys365 - DKE Cockpit
    url: $SECRET_PAGE
  - name: Double Key Encryption App
    url: $SECRET_DKE_APP
  - name: Double Key Encryption Fullpath
    url: $SECRET_DKE_KEY
  - name: Transaction Security Broker - Demo
    url: https://tsb-demo.cloudshsm.com/v1/licenseInfo
    expectedStatusCodes:
      - 200
  - name: Transaction Security Broker - Developer Program
    url: https://primusdev.cloudshsm.com/v1/licenseInfo
    icon: https://github.com/SecurosysFernandez/clouds-uptime/blob/master/assets/Transaction_Security_Broker.png
    headers:
      - "accept: application/json"
      - "Authorization: Bearer $TSB_PRIMUSDEV_TOKEN"
    expectedStatusCodes:
      - 200
  - name: Transaction Security Broker - Sandbox
    url: $SECRET_SBX_REST_API_KEY
    icon: https://github.com/SecurosysFernandez/clouds-uptime/blob/master/assets/Transaction_Security_Broker.png
  - name: Transaction Security Broker - Economy
    url: $SECRET_REST_API_KEY
    icon: https://github.com/SecurosysFernandez/clouds-uptime/blob/master/assets/Transaction_Security_Broker.png
  - name: CloudsHSM - Europe (Cluster)    
    url: $SECRET_DE_API    
    __dangerous__insecure: true
    headers:
      - "accept: application/json"
      - "Authorization: Bearer $CLUSTERS_SECRET"
    expectedStatusCodes:
      - 200
  - name: CloudsHSM - America (Cluster)  
    url: $SECRET_US_API
    __dangerous__insecure: true
    headers:
      - "accept: application/json"
      - "Authorization: Bearer $CLUSTERS_SECRET"
    expectedStatusCodes:
      - 200
  - name: CloudsHSM - Asia Pacific  
    url: $SECRET_SG_API
    __dangerous__insecure: true
    headers:
      - "accept: application/json"
      - "Authorization: Bearer $CLUSTERS_SECRET"
    expectedStatusCodes:
      - 200
  - name: CloudsHSM - Sitzerland (Cluster)   
    url: $SECRET_CH_API
    __dangerous__insecure: true
    headers:
      - "accept: application/json"
      - "Authorization: Bearer $CLUSTERS_SECRET"
    expectedStatusCodes:
      - 200
assignees: # Users to assign downtime issues (optional)
  - Daught

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.cloudshsm.com
  baseUrl: /clouds-uptime
  logoUrl: https://raw.githubusercontent.com/SecurosysFernandez/clouds-uptime/master/Clouds.png
  name: Clouds Service - RealTime uptime
  introTitle: "**Clouds Upptime** is the uptime tracker for Clouds-Service."
  introMessage: 
